# Generated by Django 3.0.5 on 2022-11-15 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_user_is_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Mailing with that name already exists.'}, max_length=150, unique=True, verbose_name='Название рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='MailingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(verbose_name='Дата отправки')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_for_user', to='mail_sender.Mailing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for_mail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
