# Generated by Django 3.0.5 on 2022-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0005_auto_20221115_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='sending_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отправки'),
        ),
    ]
