# Generated by Django 3.0.5 on 2022-11-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0006_auto_20221115_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailinguser',
            options={'verbose_name': 'Рассылка + Пользователи', 'verbose_name_plural': 'Рассылки + Пользователи'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='users',
            field=models.ManyToManyField(related_name='mail', through='mail_sender.MailingUser', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='mailinguser',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mail_sender.Mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailinguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
