# Generated by Django 3.0.5 on 2022-11-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0007_auto_20221115_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinguser',
            options={'verbose_name': 'Рассылка - Пользователи', 'verbose_name_plural': 'Рассылки - Пользователи'},
        ),
    ]
