version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./static/:/data/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  rabbit:
      restart: always
      image: "rabbitmq:3-management"
      env_file:
        - ./.env
      ports:
        - "5672:5672"
        - "15672:15672"

  celery:
    restart: always
    build:
      context: .
    command: celery worker --app=mail_system.celeryapp:app -l info
    volumes:
      - ./mail_system:/mail_system
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbit
      - backend
      - nginx