# Generated by Django 3.0.5 on 2022-11-15 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_mailing_mailinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='users',
            field=models.ManyToManyField(through='mail_sender.MailingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
