# Generated by Django 3.0.5 on 2022-11-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0008_auto_20221115_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='body',
            field=models.TextField(default='a', verbose_name='Текст рассылки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='subject',
            field=models.CharField(default='a', max_length=150, verbose_name='Тема рассылки'),
            preserve_default=False,
        ),
    ]
